# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: yarn install
        run: npm install --global yarn
      - name: check yarn version
        run: yarn --version
      - name: install dependencies
        run: yarn
      - name: build application
        run: yarn build
      - name: show build files
        run: ls -la

  check-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: show build files
        run: ls -la

