name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: yarn install
        run: npm install --global yarn
      - name: check yarn version
        run: yarn --version
      - name: install dependencies
        run: yarn
      - name: build application
        run: yarn build
      - name: show build files
        run: |
          ls -la
          cd dist/ci-cd/browser
          ls -la
      - name: Copy all file to anouther folder for deploy
        run: |
          mkdir deploy
          cp -r dist/ci-cd/browser/* deploy
          ls -la deploy
          cd deploy
          ls -la
