name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: yarn install
        run: npm install --global yarn
      - name: check yarn version
        run: yarn --version
      - name: install dependencies
        run: yarn
      - name: build application
        run: yarn build
      - name: show build files
        run: |
          ls -la
          cd dist/ci-cd/browser
          ls -la
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: angular-app
          path: dist/ci-cd/browser

  deploy:
    runs-on: self-hosted

    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: angular-app
          path: /home/ubuntu/webapp

      - name: Verify Artifacts
        run: ls -l path/on/webapp

      - name: Your Deployment Steps
        run: |
          # Add your deployment commands here
